---
title: "Week 2 Discussion"
subtitle: "Visualization Basics"
author: "Liv Hemond"
date: 2025-01-07
toc: true
format: html
editor: visual
---

```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                                    setup                                 ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#..........................load packages.........................
library(tidyverse)

#..........................import data...........................
drought <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2021/2021-07-20/drought.csv')

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                            wrangle drought data                          ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

drought_clean <- drought |>

  # select cols of interest & update names for clarity (as needed) ----
  select(date = valid_start, state_abb, drought_lvl, area_pct) |> 

  # add year, month & day cols using {lubridate} fxns ----
  # NOTE: this step isn't necessary for our plot, but I'm including as examples of how to extract different date elements from a object of class `Date` using {lubridate} ----
  mutate(year = year(date),
         month = month(date, label = TRUE, abbr = TRUE),
         day = day(date)) |>

  # add drought level conditions names ----
  mutate(drought_lvl_long = factor(drought_lvl,
                            levels = c("D4", "D3", "D2", "D1","D0", "None"),
                            labels = c("(D4) Exceptional", "(D3) Extreme",
                                       "(D2) Severe", "(D1) Moderate", 
                                       "(D0) Abnormally Dry", 
                                       "No Drought"))) |>
  
  # reorder cols ----
  relocate(date, year, month, day, state_abb, drought_lvl, drought_lvl_long, area_pct)
```


```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##       create stacked area plot of CA drought conditions through time     ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

drought_clean |> 
  
  # remove drought_lvl "None" & filter for just CA ----
  filter(drought_lvl != "None",
         state_abb == "CA") |> 
  
  # initialize ggplot (use date column instead of year) ----
  ggplot(aes(x = date, y = area_pct, fill = drought_lvl_long)) +
  
  # add stacked area plot, and reverse order so that D4 is visually closest to x axis ----
  geom_area(position = position_stack(reverse = TRUE)) +
  
  # set custom colors ----
  scale_fill_manual(values = c("#853A04", "#FF0100", "#FEC200", "#FFDA67", "#FEFF02")) +
  
  # adjust x axis breaks & remove padding between data and x axis ----
  scale_x_date(breaks = scales::breaks_pretty(n = 10),
               expand = c(0,0)) + # padding (X,Y). X multiplies by your data, Y adds that number of units

  # adjust y axis breaks, add %, and remove padding ----
  scale_y_continuous(breaks = scales::breaks_pretty(n = 10),
                     labels = scales::label_percent(scale = 1),
                     expand = c(0,0)) +
  
  # update plot title and remove axis titles
  labs(x = NULL, 
       y = NULL, 
       title = "Drought area in California",
       fill = NULL) +
  
  # remove background
  theme_minimal() +
  
  # move legend to bottom, adjust title position
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5))
```







